pages:
  tags:
    - shared
  stage: deploy
  script:
    - mkdir public
    - cp chiroptera-tree.html public/index.html
    - cp index.html public/lookup.html
    - cp -r data public/
    - rm -rf public/data/raw
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
