"""Build marine-mammal-tree.html from chiroptera-tree.html.

Run:  uv run python data/build_marine_mammal_page.py

chiroptera-tree.html is the master. This copies it verbatim and swaps only
content: prose, the four hand-authored data blocks (generated by gen_marine.py
from MDD), the data-file paths, and the strings that name the animals. Every
replacement is anchored on an exact string and fails loudly if it misses, so
the two pages cannot silently drift apart structurally.
"""
import re, os, sys

import build_marine_mammal_data_blocks as data

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "chiroptera-tree.html")
DST = os.path.join(REPO, "marine-mammal-tree.html")

html = open(SRC, encoding="utf-8").read()
blocks = data.blocks

def grab(name):
    """Pull one generated const block out of blocks.js.

    TREE is an array literal and closes on "]};" rather than "};" -- without
    that alternative the non-greedy match runs straight past it and swallows
    the next block whole.
    """
    m = re.search(r"^const %s = .*?^\]?};$" % name, blocks, re.S | re.M)
    if not m:
        sys.exit("generated block not found: " + name)
    return m.group(0)

hits = []
def sub(old, new, count=1):
    global html
    n = html.count(old)
    if n != count:
        sys.exit("ANCHOR MISS (%d, expected %d): %s" % (n, count, old[:90].replace("\n", " ")))
    html = html.replace(old, new)
    hits.append(old[:60].replace("\n", " "))

def sub_region(start, end, new):
    """Replace from `start` through `end` inclusive."""
    global html
    i = html.find(start)
    j = html.find(end, i)
    if i < 0 or j < 0:
        sys.exit("REGION MISS: %s ... %s" % (start[:60], end[:60]))
    html = html[:i] + new + html[j + len(end):]
    hits.append("region " + start[:50].replace("\n", " "))

# ----------------------------------------------------------------- head / chrome
sub("<title>Chiroptera — the ranks and branches of bats</title>",
    "<title>Marine mammals — three lineages that went back to the sea</title>")

sub('<a class="tb-brand" href="#top">The branching of <em>bats</em></a>',
    '<a class="tb-brand" href="#top">Back to the <em>sea</em></a>')

# cross-links, both ways: the master carries "Marine mammals ->", so the clone
# carries the return trip in exactly the same nav slot
sub("""      <a href="marine-mammal-tree.html">Marine mammals &rarr;</a>""",
    """      <a href="chiroptera-tree.html">Bats &rarr;</a>""")

sub('placeholder="Search any bat…"', 'placeholder="Search any marine mammal…"')
sub('aria-label="Cladogram of the 21 living bat families"',
    'aria-label="Cladogram of the 18 living marine mammal families"')
sub("World map, click a country to list its bats", "World map, click a country to list its marine mammals")
sub("/* ---- browse-by-country map: click a country, list bats confirmed there ---- */",
    "/* ---- browse-by-country map: click a country, list the marine mammals confirmed there ---- */")

# ------------------------------------------------------------------- intro card
sub_region('    <p class="eyebrow">', '</div>\n</section>',
"""    <p class="eyebrow">Three lineages, one way of life</p>
    <h1>Back to the <em>sea</em></h1>
    <p class="deck">Bats are a clade: every one of them descends from a single flying ancestor. &ldquo;Marine mammal&rdquo; is not. It is a job description that three unrelated groups of land mammals filled independently — whales from hoofed stock, sirenians from the elephant side of the tree, seals from the carnivorans — and the resemblance between them is something water imposed, not something they inherited.</p>
  </div>
  <div class="figures">
    <div class="fig"><b>18</b><span>Living families</span></div>
    <div class="fig"><b>3</b><span>Lineages</span></div>
    <div class="fig"><b id="genera-total">—</b><span>Genera</span></div>
    <div class="fig"><b>144</b><span>Species</span></div>
  </div>
</section>""")

# ----------------------------------------------------------------- ranks section
sub("""      <p class="fold-lede">Background: what a rank actually is, and how a single bat is filed from kingdom down to species.</p>""",
    """      <p class="fold-lede">Background: what a rank actually is, and where four marine mammals land when you file them from kingdom down to species.</p>""")

sub("""      <p class="lede">A rank is just a level of nesting. Each step down describes a smaller, more closely related group, and every group at every level is contained entirely inside the one above it. Family sits in the middle: broad enough to share an obvious body plan and way of life, narrow enough that its members are unmistakably kin.</p>
      <p class="lede">Pick a bat and watch the ladder narrow. The bar under each rung shows how many bat species fall inside that group.</p>""",
    """      <p class="lede">A rank is just a level of nesting. Each step down describes a smaller, more closely related group, and every group at every level is contained entirely inside the one above it. Family sits in the middle: broad enough to share an obvious body plan and way of life, narrow enough that its members are unmistakably kin.</p>
      <p class="lede">Follow any of the four below and watch where it splits from the others. They share Kingdom, Phylum and Class — and then nothing. There is no rung at which &ldquo;marine mammal&rdquo; appears, because the group was never one thing to begin with. Note where the whales sit: inside Artiodactyla, the even-toed hoofed mammals, alongside the hippos that are their closest living relatives.</p>""")

sub("""      <div class="switch" role="group" aria-label="Choose a worked example">
        <button type="button" data-ex="0" aria-pressed="true">Common pipistrelle</button>
        <button type="button" data-ex="1" aria-pressed="false">Large flying fox</button>
        <button type="button" data-ex="2" aria-pressed="false">Common vampire bat</button>
      </div>""",
    """      <div class="switch" role="group" aria-label="Choose a worked example">
        <button type="button" data-ex="0" aria-pressed="true">Blue whale</button>
        <button type="button" data-ex="1" aria-pressed="false">Killer whale</button>
        <button type="button" data-ex="2" aria-pressed="false">Dugong</button>
        <button type="button" data-ex="3" aria-pressed="false">Walrus</button>
      </div>""")

# ------------------------------------------------------------------ atlas prose
sub("""      <p class="fold-lede">The same content as the tree, laid out flat and filterable by range, diet, roost, echolocation or regional checklist. Filtering here also dims the tree above.</p>""",
    """      <p class="fold-lede">The same content as the tree, laid out flat and filterable by ocean, diet, where it rests, biosonar or regional checklist. Filtering here also dims the tree above.</p>""")

sub("""      <p class="lede">All 21 families opened up: subfamilies, tribes where they are used, and every genus, with the number of species in each. Genera marked with a dot open one level further, to the species themselves.</p>""",
    """      <p class="lede">All 18 families opened up, grouped by lineage: subfamilies, tribes where they are used, and every genus, with the number of species in each. Genera marked with a dot open one level further, to the species themselves.</p>""")

sub("""      <p class="lede">Where a genus is small, every species is listed. Where it is large — <em>Myotis</em> has 143 — you get a labelled selection rather than a wall of Latin, and the panel says so. <span id="sp-coverage"></span> Each species carries an echolocation line: a measured description where one exists, otherwise the family profile, shown in grey italics so you can tell the two apart.</p>""",
    """      <p class="lede">Every genus lists every one of its species. With 144 species in total there is no need for the labelled-selection compromise a group of 1,500-plus would force — the largest genus here, <em>Mesoplodon</em>, has 16. <span id="sp-coverage"></span></p>""")

sub("""      <p class="lede">The filters below work on genera, and the cladogram above dims to match. Diet, roost and range are labelled at genus level, which is blunt: a genus of 130 species will always have exceptions to whatever label it carries. Echolocation is labelled at family level. The two regional checklists are curated species lists, not derived from the range data.</p>""",
    """      <p class="lede">The filters below work on genera, and the cladogram above dims to match. Ocean, diet and haul-out are labelled at genus level, which is blunt: a wide-ranging genus will always have exceptions to whatever label it carries. Biosonar is labelled at family level, and only as a yes or no — see the note in the footer on why there are no call figures here. The two regional checklists are curated species lists, not derived from the range data.</p>""")

# ---------------------------------------------------------------------- sources
sub_region('  <div class="lede-block">\n    <p class="lede">Each species above carries three links.',
           '</div>\n</section>\n\n<footer>',
"""  <div class="lede-block">
    <p class="lede">Each species above carries links to <em>search results</em>, not to individual pages — a search box always resolves, whereas a guessed page address often does not. Coverage is good for the large whales, the temperate dolphins and the northern seals, and thin for beaked whales, which is a fair reflection of how little anyone has seen of them.</p>
  </div>

  <div class="sources">
    <div class="src"><a href="https://www.marinemammalscience.org/species-information/list-marine-mammal-species-subspecies/" target="_blank" rel="noopener noreferrer">Society for Marine Mammalogy</a>
      <p>Its Committee on Taxonomy maintains the standing list of marine mammal species and subspecies, revised annually. This is the specialist authority for the group, and the reference to check this page against — it will drift ahead of what MDD has folded in.</p></div>
    <div class="src"><a href="https://cis.whoi.edu/science/B/whalesounds/index.cfm" target="_blank" rel="noopener noreferrer">Watkins Marine Mammal Sound Database</a>
      <p>Woods Hole's archive of roughly 70 years of recordings, covering about 60 species — the closest thing this group has to a single open call library. Start here for what any of these animals actually sound like.</p></div>
    <div class="src"><a href="https://www.inaturalist.org" target="_blank" rel="noopener noreferrer">iNaturalist</a>
      <p>Photographs of live animals, community-identified. Strong for coastal species and whale-watching routes, sparse for anything that lives past the shelf edge. This is what the "photos" link searches.</p></div>
    <div class="src"><a href="https://www.gbif.org" target="_blank" rel="noopener noreferrer">GBIF</a>
      <p>Aggregated occurrence records from museums, surveys and strandings worldwide. Good for answering "where has this actually been recorded", and the source of the country supplement merged into the map on this page.</p></div>
    <div class="src"><a href="https://www.iucnredlist.org" target="_blank" rel="noopener noreferrer">IUCN Red List</a>
      <p>Conservation status, threats and range maps, written by specialist assessors. The place to check before trusting any distribution statement here — and the source for the status shown on every species record.</p></div>
    <div class="src"><a href="https://www.mammaldiversity.org/explore/taxonomy-table/" target="_blank" rel="noopener noreferrer">Mammal Diversity Database</a>
      <p>The American Society of Mammalogists' running list of every mammal species, updated a few times a year and downloadable as CSV. Its taxonomy table is the source for every count, rank and country on this page. Version 2.5 places all 102 cetaceans inside Artiodactyla, and unlike its bat coverage it fills in subfamily and tribe for these families itself.</p></div>
    <div class="src"><a href="https://obis.org" target="_blank" rel="noopener noreferrer">OBIS</a>
      <p>The Ocean Biodiversity Information System — the marine counterpart to GBIF, pooling survey and tracking data. Better than any country list for animals whose real range is a current, a shelf edge or a migration corridor rather than a coastline.</p></div>
    <div class="src"><a href="https://www.naturalearthdata.com" target="_blank" rel="noopener noreferrer">Natural Earth</a>
      <p>Public-domain map data. The range map is drawn from Natural Earth's country outlines with small islands marked as dots, and — unlike the bat page's map — it keeps Antarctica, which 28 of these species need. The countries themselves come from MDD and GBIF, not from Natural Earth: the map only draws what the checklist already says.</p></div>
  </div>
</section>

<footer>""")

# ----------------------------------------------------------------------- footer
sub_region("  <p><b>How firm is any of this?</b>", "</footer>",
"""  <p><b>How firm is any of this?</b> The three lineages are not in doubt, and neither is the awkward fact underneath them: they are not each other's closest relatives. Whales sit inside Artiodactyla next to hippos, sirenians belong with elephants and hyraxes, pinnipeds with bears and weasels. Below that it softens. Whether the pinnipeds entered the water once or twice was argued for a century — one origin is now the settled answer — and the split drawn here between Otarioidea and Phocoidea is a convenience, not a consensus. Inside Delphinidae the arrangement is frankly unstable, which is why MDD leaves <i>Orcinus</i>, <i>Lagenorhynchus</i> and <i>Leucopleurus</i> in <i>incertae sedis</i> rather than forcing them into a subfamily.</p>
  <p><b>Where the numbers come from.</b> Every count here is taken from the Mammal Diversity Database v2.5: 144 living and recently extinct species, 67 genera, 18 families. Unlike the bat page, no rank on this page is supplied by hand — MDD's own table carries subfamily and tribe for these families, so the atlas groupings, the cladogram and the ladder are all read straight out of it. The lineage totals are Cetacea 102, Pinnipedia 37, Sirenia 5.</p>
  <p><b>Why there are no call figures.</b> The toothed whales are among the most accomplished echolocators alive, and the sperm whale's click is the loudest sound any animal makes. None of that is quantified here. The bat page carries a hand-compiled table of call type, duty cycle and peak frequency per family; no equivalent reference was compiled for these animals, and inventing one would have produced numbers that look citable and are not. The filter therefore answers only "does this family hunt with biosonar", which is a fact rather than a measurement. Pinnipeds answer no: seals track prey by hearing, sight, and in several species by reading the hydrodynamic wake a fish leaves behind with their whiskers, which is not sonar.</p>
  <p><b>The numbers move, and three have stopped.</b> Species counts here are rising for the same reason they are everywhere — genetics splitting one widespread species into several. MDD v2.5 breaks the killer whale into three, cuts <i>Lagenorhynchus</i> down to a single species with the rest moved to <i>Leucopleurus</i> and <i>Aethalodelphis</i>, and folds the grey whale into Balaenopteridae. Three species in this list are already gone: Steller's sea cow, hunted out within 27 years of being described; the Caribbean monk seal; and the Japanese sea lion. The baiji is still listed as living, which is a formality — a full survey of the Yangtze in 2006 found none.</p>
</footer>""")

# ================================================================= JS data blocks
sub("const TOTAL = 1506;",
    "// the largest group any of these sit inside — Artiodactyla, which holds the\n"
    "// whales along with every hoofed mammal — so the ladder bars stay in scale\nconst TOTAL = 374;")

# --- worked examples
i = html.find("const examples = [")
j = html.find("\n];", i)
html = html[:i] + """const examples = [
  {
    label:"Blue whale",
    rows:[
      {rank:"Kingdom",  taxon:"Animalia", above:true},
      {rank:"Phylum",   taxon:"Chordata", above:true},
      {rank:"Class",    taxon:"Mammalia", above:true},
      {rank:"Order",       taxon:"Artiodactyla",      n:374, gloss:"Even-toed hoofed mammals — and, nested well inside them, every whale. Their closest living relatives are the hippos."},
      {rank:"Suborder",    taxon:"Cetacea",           n:102, gloss:"Whales, dolphins and porpoises. Fully aquatic for about 40 million years."},
      {rank:"Infraorder",  taxon:"Mysticeti",         n:16,  gloss:"Baleen instead of teeth: filter feeders that strain prey from the water."},
      {rank:"Superfamily", taxon:"Balaenopteroidea",  n:11,  gloss:"The lunge feeders, with pleated throats that balloon out around a mouthful."},
      {rank:"Family",      taxon:"Balaenopteridae",   n:11,  gloss:"Rorquals — and since MDD folded it in, the grey whale."},
      {rank:"Genus",       taxon:"Balaenoptera",      n:9,   gloss:"The blue, fin, sei, minke and Bryde's whales."},
      {rank:"Species",     taxon:"Balaenoptera musculus", n:1, ital:true, terminal:true, gloss:"The largest animal that has ever lived — larger than any dinosaur, and it eats krill."}
    ]
  },
  {
    label:"Killer whale",
    rows:[
      {rank:"Kingdom",  taxon:"Animalia", above:true},
      {rank:"Phylum",   taxon:"Chordata", above:true},
      {rank:"Class",    taxon:"Mammalia", above:true},
      {rank:"Order",       taxon:"Artiodactyla",   n:374, gloss:"Same hoofed ancestry as the blue whale."},
      {rank:"Suborder",    taxon:"Cetacea",        n:102, gloss:"All whales, dolphins and porpoises."},
      {rank:"Infraorder",  taxon:"Odontoceti",     n:86,  gloss:"Teeth instead of baleen, and active biosonar — the branch that hunts by sound."},
      {rank:"Superfamily", taxon:"Delphinoidea",   n:51,  gloss:"Dolphins, porpoises, beluga and narwhal."},
      {rank:"Family",      taxon:"Delphinidae",    n:41,  gloss:"Oceanic dolphins — the largest and youngest cetacean family."},
      {rank:"Subfamily",   taxon:"incertae sedis", n:null, gloss:"Latin for \\u201cof uncertain position\\u201d. The killer whale is hard to place inside its own family, so MDD declines to guess.", skip:true},
      {rank:"Genus",       taxon:"Orcinus",        n:3,   gloss:"Split into three species in recent revisions, where older references have one."},
      {rank:"Species",     taxon:"Orcinus orca",   n:1, ital:true, terminal:true, gloss:"The ocean's top predator, with hunting traditions that differ between neighbouring groups and are taught, not inherited."}
    ]
  },
  {
    label:"Dugong",
    rows:[
      {rank:"Kingdom",  taxon:"Animalia", above:true},
      {rank:"Phylum",   taxon:"Chordata", above:true},
      {rank:"Class",    taxon:"Mammalia", above:true},
      {rank:"Order",       taxon:"Sirenia",       n:5,  gloss:"An entire order of five species, all of them marine or riverine grazers. Their nearest relatives on land are elephants and hyraxes."},
      {rank:"Family",      taxon:"Dugongidae",    n:2,  gloss:"The dugong, and Steller's sea cow — extinct since 1768."},
      {rank:"Subfamily",   taxon:"Dugonginae",    n:1,  gloss:"One surviving species."},
      {rank:"Genus",       taxon:"Dugong",        n:1,  gloss:"A genus of one, and the only sirenian that never enters fresh water."},
      {rank:"Species",     taxon:"Dugong dugon",  n:1, ital:true, terminal:true, gloss:"Crops seagrass at the root, leaving visible furrows across the meadow. The likely origin of the mermaid story."}
    ]
  },
  {
    label:"Walrus",
    rows:[
      {rank:"Kingdom",  taxon:"Animalia", above:true},
      {rank:"Phylum",   taxon:"Chordata", above:true},
      {rank:"Class",    taxon:"Mammalia", above:true},
      {rank:"Order",       taxon:"Carnivora",   n:320, gloss:"Cats, dogs, bears, weasels — and the seals, which are carnivorans that went to sea."},
      {rank:"Suborder",    taxon:"Caniformia",  n:187, gloss:"The dog-like half of the order. Pinnipeds sit in here, not with the cats."},
      {rank:"Infraorder",  taxon:"Arctoidea",   n:147, gloss:"Bears, weasels, raccoons and seals. \\u201cPinnipedia\\u201d itself is a clade, not a rank MDD records."},
      {rank:"Family",      taxon:"Odobenidae",  n:1,   gloss:"A family reduced to a single living species."},
      {rank:"Subfamily",   taxon:"Odobeninae",  n:1,   gloss:"Ranks below family survive here even though only one animal is left to fill them."},
      {rank:"Tribe",       taxon:"Odobenini",   n:1,   gloss:"An optional rank, retained from a time when the family had more members to sort."},
      {rank:"Genus",       taxon:"Odobenus",    n:1,   gloss:"One genus, one species."},
      {rank:"Species",     taxon:"Odobenus rosmarus", n:1, ital:true, terminal:true, gloss:"Finds clams in the dark with 600-odd whiskers and sucks them out of their shells."}
    ]
  }
];""" + html[j + len("\n];"):]
hits.append("examples[]")

# --- generated blocks
def swap_const(name):
    global html
    i = html.find("const %s = {" % name)
    if i < 0:
        sys.exit("const not found: " + name)
    j = html.find("\n};", i)
    html = html[:i] + grab(name) + html[j + len("\n};"):]
    hits.append("const " + name)

for name in ("F", "ATLAS", "SP", "TRAW", "ETAG"):
    swap_const(name)

# TREE is an object literal ending in "]};"
i = html.find('const TREE = {name:"Chiroptera"')
j = html.find("\n]};", i)
html = html[:i] + grab("TREE").rstrip() + html[j + len("\n]};"):]
hits.append("const TREE")

# --- echolocation datasets: kept as empty objects so every code path the master
# has stays exactly as it is and simply renders nothing, rather than being cut.
i = html.find("const ECHO = {")
j = html.find("\n};", i)
html = html[:i] + """/* No marine equivalent of the bat page's per-family echolocation reference was
   compiled, and inventing call figures would produce numbers that look citable
   and are not. These stay empty on purpose: every code path below is the
   master's, and simply renders nothing. Whether a family uses biosonar at all
   is a fact, and lives in ETAG. */
const ECHO = {};""" + html[j + len("\n};"):]
hits.append("const ECHO -> {}")

i = html.find("const ESP = {")
j = html.find("\n};", i)
html = html[:i] + "const ESP = {};" + html[j + len("\n};"):]
hits.append("const ESP -> {}")

# --- regional checklists
i = html.find("const CHECK = {")
j = html.find("\n};", i)
html = html[:i] + """const CHECK = {
dk:{name:"Danish waters", sp:["Phocoena phocoena","Phoca vitulina","Halichoerus grypus",
 "Lagenorhynchus albirostris","Balaenoptera acutorostrata"]},
gb:{name:"British & Irish waters", sp:["Phocoena phocoena","Tursiops truncatus","Delphinus delphis",
 "Leucopleurus acutus","Lagenorhynchus albirostris","Grampus griseus","Globicephala melas",
 "Balaenoptera acutorostrata","Balaenoptera physalus","Megaptera novaeangliae","Orcinus orca",
 "Phoca vitulina","Halichoerus grypus"]}
};""" + html[j + len("\n};"):]
hits.append("const CHECK")

# --- links: xeno-canto does not cover marine mammals
sub("""const LINKS = [
  ["wikipedia", n => "https://en.wikipedia.org/w/index.php?search=" + encodeURIComponent(n)],
  ["photos",    n => "https://www.inaturalist.org/search?q=" + encodeURIComponent(n)],
  ["calls",     n => "https://xeno-canto.org/explore?query=" + encodeURIComponent(n)]
];""",
    """const LINKS = [
  ["wikipedia", n => "https://en.wikipedia.org/w/index.php?search=" + encodeURIComponent(n)],
  ["photos",    n => "https://www.inaturalist.org/search?q=" + encodeURIComponent(n)],
  ["records",   n => "https://www.gbif.org/species/search?q=" + encodeURIComponent(n)]
];""")

# --- filter definitions
i = html.find("const FDEFS = [")
j = html.find("\n];", i)
html = html[:i] + """const FDEFS = [
  {k:'chk', label:'Regional checklist', single:true, opts:[['dk','Danish waters · 5 spp.'],['gb','British & Irish waters · 13 spp.']]},
  {k:'r', label:'Where it lives', opts:[['glob','All oceans'],['atl','Atlantic'],['pac','Pacific'],['ind','Indian Ocean'],['arc','Arctic'],['sou','Southern Ocean'],['riv','Rivers & estuaries']]},
  {k:'d', label:'What it eats', opts:[['fis','Fish'],['squ','Squid & cephalopods'],['kri','Krill & plankton'],['ben','Seabed invertebrates'],['ver','Birds & mammals'],['veg','Seagrass & water plants']]},
  {k:'e', label:'Hunts with biosonar', opts:[['bio','Yes — active biosonar'],['none','No']]},
  {k:'ro', label:'Where it rests or breeds', opts:[['sea','Never leaves the water'],['ice','Pack ice'],['land','Beaches & rocky shores'],['riv','Rivers']]},
  {k:'c', label:'Lineage', opts:[['Mysticeti','Mysticeti'],['Odontoceti','Odontoceti'],['Sirenia','Sirenia'],['Pinnipedia','Pinnipedia']]}
];""" + html[j + len("\n];"):]
hits.append("const FDEFS")

# --- counts baked into the filter summary text
sub("""      (nFam===1?' of the 21 families.':' of the 21 families.');""",
    """      (nFam===1?' of the 18 families.':' of the 18 families.');""")
sub("""    fsummary.innerHTML = 'Showing all <b>'+generaTotal+' genera</b> in 21 families.""",
    """    fsummary.innerHTML = 'Showing all <b>'+generaTotal+' genera</b> in 18 families.""")

# ------------------------------------------------------------------- data wiring
sub("""Promise.all([
  bundled('d-taxonomy', 'data/chiroptera_taxonomy.json'),
  bundled('d-echo', 'data/echolocation_reference.json'),
  bundled('d-danish', 'data/danish_names.json'),
  bundled('d-countries', 'data/gbif_country_supplement.json')
]).then(([tax, echo, danish, countrySupp])=>{
  luState.species = tax.species;
  luState.echo = echo;""",
    """Promise.all([
  bundled('d-taxonomy', 'data/marine_mammal_taxonomy.json'),
  bundled('d-danish', 'data/marine_mammal_danish_names.json'),
  bundled('d-countries', 'data/marine_mammal_gbif_country_supplement.json')
]).then(([tax, danish, countrySupp])=>{
  luState.species = tax.species;
  // no echolocation reference ships for these animals; luFindEcho already has
  // the honest fallback for it, and the drawer says so per species
  luState.echo = null;""")

sub("""  luInput.placeholder = 'Search ' + tax._meta.speciesCount.toLocaleString() + ' bats…';""",
    """  luInput.placeholder = 'Search ' + tax._meta.speciesCount.toLocaleString() + ' marine mammals…';""")

sub("bundled('d-worldmap', 'data/world_map.json')",
    "bundled('d-worldmap', 'data/marine_world_map.json')")

# the drawer's provenance line
sub("""    '<p class="lu-prov">Taxonomy: Mammal Diversity Database v2.5 — <a href="https://doi.org/10.5281/zenodo.21654811" target="_blank" rel="noopener">doi:10.5281/zenodo.21654811</a>. ' +
    'Echolocation figures are a family/genus reference compiled from standard comparative literature (Jones &amp; Holderied 2007; Fenton &amp; Simmons 2015; Neuweiler 2000). ' +
    'Danish names come from <a href="https://www.gbif.org" target="_blank" rel="noopener">GBIF</a> vernacular-name records and are shown only where a genuine Danish name is on record.</p>';""",
    """    '<p class="lu-prov">Taxonomy: Mammal Diversity Database v2.5 — <a href="https://doi.org/10.5281/zenodo.21654811" target="_blank" rel="noopener">doi:10.5281/zenodo.21654811</a>, which places the cetaceans inside Artiodactyla. ' +
    'No echolocation reference is shipped for these species — see the footer for why. ' +
    'Danish names come from <a href="https://www.gbif.org" target="_blank" rel="noopener">GBIF</a> vernacular-name records and are shown only where a genuine Danish name is on record.</p>';""")

# --------------------------------------------------------------- bundled payload
sub("""<script type="application/json" id="d-taxonomy">
INLINE data/chiroptera_taxonomy.json
</script>
<script type="application/json" id="d-echo">
INLINE data/echolocation_reference.json
</script>
<script type="application/json" id="d-danish">
INLINE data/danish_names.json
</script>
<script type="application/json" id="d-countries">
INLINE data/gbif_country_supplement.json
</script>
<script type="application/json" id="d-worldmap">
INLINE data/world_map.json
</script>""",
    """<script type="application/json" id="d-taxonomy">
INLINE data/marine_mammal_taxonomy.json
</script>
<script type="application/json" id="d-danish">
INLINE data/marine_mammal_danish_names.json
</script>
<script type="application/json" id="d-countries">
INLINE data/marine_mammal_gbif_country_supplement.json
</script>
<script type="application/json" id="d-worldmap">
INLINE data/marine_world_map.json
</script>""")

open(DST, "w", encoding="utf-8", newline="\n").write(html)
print("applied %d replacements" % len(hits))
print("wrote %s (%d KB)" % (DST, os.path.getsize(DST) / 1024))
leftover = re.findall(r"\b[Bb]at(s)?\b|Chiroptera|Myotis|Pteropus", html)
print("leftover bat references:", len(leftover))
